export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL';

export const ADD_LIST = 'ADD_LIST';
export const ADD_LIST_START = 'ADD_LIST_START';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const REMOVE_LIST = 'REMOVE_LIST';
export const REMOVE_LIST_START = 'REMOVE_LIST_START';
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS';
export const REMOVE_LIST_FAIL = 'REMOVE_LIST_FAIL';

export const UPDATE_ITEM_STATUS = 'UPDATE_ITEM_STATUS';
export const UPDATE_ITEM_STATUS_START = 'UPDATE_ITEM_STATUS_START';
export const UPDATE_ITEM_STATUS_SUCCESS = 'UPDATE_ITEM_STATUS_SUCCESS';
export const UPDATE_ITEM_STATUS_FAIL = 'UPDATE_ITEM_STATUS_FAIL';

export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_ITEM_START = 'REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';
